name: Deploy to Testserver

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - testserver-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --build-arg CONFIG_CONTENT='${{ secrets.CONFIG }}' -t qissy .

      - name: Deploy Container
        run: |
          docker stop qissy || true
          docker rm qissy || true
          docker run -d --name qissy -p 127.0.0.1:${{ secrets.TESTSERVER_DEPLOYMENT_PORT }}:8000 --network ${{ secrets.TESTSERVER_DEPLOYMENT_NETWORK }} qissy
